/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage/index.vue')['default']
    Idnex: typeof import('./src/components/NavBar/idnex.vue')['default']
    Input: typeof import('./src/components/Input/index.vue')['default']
    InputDate: typeof import('./src/components/InputDate/index.vue')['default']
    InputSearch: typeof import('./src/components/InputSearch/index.vue')['default']
    InputSelect: typeof import('./src/components/inputSelect/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar/index.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/index.vue')['default']
    NotificationDropdown: typeof import('./src/components/NotificationDropdown/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar/index.vue')['default']
  }
}
